spring.application.name=fixly

## porta
server.port=8081

#banco de SQL ORACLE
spring.datasource.url=jdbc:oracle:thin:@localhost:1521:xe
spring.datasource.username=dbafixly
spring.datasource.password=123
spring.datasource.driver-class-name=oracle.jdbc.OracleDriver

#sql persistencia
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.hibenate.ddl-auto=none  

# swagger-ui custom path
springdoc.swagger-ui.path=/swagger-ui.html